/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JMenuItem;
import modelos.fondos.FondoPrincipal;

/**
 *
 * @author usuario
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    public JMenuItem getItemAdministrador() {
        return itemAdministrador;
    }

    public void setItemAdministrador(JMenuItem itemAdministrador) {
        this.itemAdministrador = itemAdministrador;
    }

    public JMenuItem getItemCliente() {
        return itemCliente;
    }

    public void setItemCliente(JMenuItem itemCliente) {
        this.itemCliente = itemCliente;
    }

    public JMenuItem getItemIniciarSeision() {
        return itemIniciarSeision;
    }

    public void setItemIniciarSeision(JMenuItem itemIniciarSeision) {
        this.itemIniciarSeision = itemIniciarSeision;
    }

    public JMenuItem getItemRepartidor() {
        return itemRepartidor;
    }

    public void setItemRepartidor(JMenuItem itemRepartidor) {
        this.itemRepartidor = itemRepartidor;
    }

    public JMenuItem getItemSalir() {
        return itemSalir;
    }

    public void setItemSalir(JMenuItem itemSalir) {
        this.itemSalir = itemSalir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPrincipal();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        itemIniciarSeision = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuRegistrar = new javax.swing.JMenu();
        itemCliente = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemAdministrador = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        itemRepartidor = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        menuOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/folder.png"))); // NOI18N
        menuOpciones.setText("Opciones");

        itemIniciarSeision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log_in.png"))); // NOI18N
        itemIniciarSeision.setText("Iniciar Sesion");
        menuOpciones.add(itemIniciarSeision);
        menuOpciones.add(jSeparator2);

        menuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/register.png"))); // NOI18N
        menuRegistrar.setText("Registrar");

        itemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        itemCliente.setText("Cliente");
        menuRegistrar.add(itemCliente);
        menuRegistrar.add(jSeparator4);

        itemAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gerente.png"))); // NOI18N
        itemAdministrador.setText("Administrador");
        menuRegistrar.add(itemAdministrador);
        menuRegistrar.add(jSeparator5);

        itemRepartidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repartidor.png"))); // NOI18N
        itemRepartidor.setText("Repartidor");
        menuRegistrar.add(itemRepartidor);

        menuOpciones.add(menuRegistrar);
        menuOpciones.add(jSeparator3);

        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        itemSalir.setText("Salir");
        menuOpciones.add(itemSalir);

        jMenuBar1.add(menuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAdministrador;
    private javax.swing.JMenuItem itemCliente;
    private javax.swing.JMenuItem itemIniciarSeision;
    private javax.swing.JMenuItem itemRepartidor;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenu menuRegistrar;
    // End of variables declaration//GEN-END:variables
}
